<?php

namespace LicoboxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * caraterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class caraterRepository extends EntityRepository
{
}
