<?php

namespace LicoboxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * t_licorneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class t_licorneRepository extends EntityRepository
{
}
