LicoboxBundle\Entity\name:
    type: entity
    table: null
    repositoryClass: LicoboxBundle\Repository\nameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
